# -*- coding: utf-8 -*-
"""ADS Exp3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iEq-GC4L0B8_9T84gL6e5quucwWNIK-y
"""

!pip install pyglet

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from IPython import display

df = pd.read_csv("/content/sample_data/tesla.csv")

df.shape

plt.figure(figsize=(16,8))
plt.title('Close Price History')
plt.plot(df['Close'], color='red')
plt.xlabel('Date', fontsize=18)
plt.ylabel('Close Price USD', fontsize = 18)
plt.show()

sns.histplot(df["High"], kde=True, color="m")

sns.displot(df["High"], kde=True, color="m")

sns.jointplot(x = "Open", y = "Close",
              kind = "scatter", data = df)

plt.show()

sns.histplot(data=df, x="Open")

fig = go.Figure(data=go.Ohlc(x=df['Date'],
                    open=df['Open'],
                    high=df['High'],
                    low=df['Low'],
                    close=df['Close']))
fig.show()

import matplotlib.pyplot as plt
plt.scatter(df['Open'], df['Close'], c ="blue")

sns.pairplot(df)
plt.show()

#column chart plot between 2 attributes
df1 = df.head(10)
df1.plot.bar()
plt.bar(df1['High'], df1['Low'])
plt.xlabel("High")
plt.ylabel("Low")
plt.show()

import plotly.express as px
df1=df.head(15)
fig = px.line(df1, x="Date", y="Volume")
fig.show()

#Density Chart
df['Adj Close'].plot.density(color='red')
plt.title('Density plot for Adj Close')
plt.show()