# -*- coding: utf-8 -*-
"""ADS Exp7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H4dxD-NaIap8Cfq2JrCjKBs-Zy-JqsXg
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from pycaret.datasets import get_data
df = get_data('anomaly')
df.head()

df.describe()

df.columns

sns.boxplot(x="variable", y="value", data=pd.melt(df))
plt.show()

sns.pairplot(df)

from pycaret.anomaly import *
setup = setup(df, session_id = 123)

models()

lof = create_model('lof')
plot_model(lof)

knn = create_model('knn')
plot_model(knn)

knn_predictions = predict_model(knn, data = df)

knn_predictions

from sklearn import datasets
df = datasets.load_iris()
X = df.data
y = df.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)

fitted = knn.fit(X_train, y_train)

pred = knn.predict(X_test)

from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(pred, y_test))

import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv('/content/sample_data/boston.csv')
df.head()

df.shape

df['TAX'].describe()

sns.boxplot(df['TAX'])

sns.distplot(df['TAX'])

"""## Winsorization"""

upper_limit = df["TAX"].quantile(0.99)
lower_limit = df['TAX'].quantile(0.01)

df['TAX'] = np.where(df['TAX'] > upper_limit, upper_limit, 
                         np.where(df['TAX'] < lower_limit, lower_limit, df['TAX']))

df['TAX'].describe()

sns.distplot(df['TAX'])

sns.boxplot(df['TAX'])